### ISSUE TITLE
Push new version to Chrome Web Store

### ISSUE THREAD

**Issue by deSagaz** [mjumelet/chrome_manual_gps#1]

**Comment by deSagaz** [comment]
Perhaps worthwhile to do still?

**Comment by deSagaz** [comment]
Hey Maurice,

Could you update the chrome web store version still? It keeps bugging me about the dangers of self-installing it. [The review thread](https://chrome.google.com/webstore/detail/manual-geolocation/jpiefjlgcjmciajdcinaejedejjfjgki) is also a bit of a downer at the moment 😉

**Comment by mjumelet** [comment]
I updated the package with your edition, might take some time to update
itself

Op wo 30 okt. 2019 om 22:15 schreef Ivar Troost <notifications@github.com>:

**Comment by deSagaz** [comment]
Awesome! It's online now 🎉
